### ISSUE TITLE
Support equations and eqnarrays in MediaWiki

### ISSUE THREAD

**Issue by dginev** [DRMF/DRMF#1]
We want to be able to write:

```
\begin{eqnarray}
&& a =b \nonumber \\[2cm]
&& c = d \nonumber
\end{eqnarray}
```

in the MarkDown of a page, with or without <math> tags around it and get the sensible HTML out. Ideally we can also reconsider using dollar signs etc. instead of the <math> tags.

**Comment by physikerwelt** [comment]
@HowardCohl the problem remains unchanged. Do we need this in the near future?

**Comment by HowardCohl** [comment]
We are not going to need eqnarray environments in DRMF.
