### ISSUE TITLE
Copy the semantic TeX from formulas

### ISSUE THREAD

**Issue by dginev** [DRMF/DRMF#40]
Once we can preserve the semantic to the output, as described in:
https://trac.mathweb.org/LaTeXML/ticket/1756

we should add the trivial extension to the JOBAD MathMenu module, which changes the "Copy TeX" into two submenus "Copy raw TeX" and "Copy Author's TeX" (i.e. before it got expanded, and still had all DLMF macros in place).

**Comment by physikerwelt** [comment]
![screenshot-wilson - devwiki - mozilla firefox](https://cloud.githubusercontent.com/assets/2777736/6781783/914c57ae-d146-11e4-80fc-cac5e5121f78.png)
Can be done with Firefox extension MathML Copy
https://addons.mozilla.org/de/firefox/addon/mathml-copy/?src=userprofile
