### ISSUE TITLE
Bag of words Search Engine

### ISSUE THREAD

**Issue by dginev** [DRMF/DRMF#41]
Basically Howard tells me that he wants Bruce's search engine applied to DRMF. The desire is to have a "bag of keywords" search, essentially extending a mint Lucene isntallation with special treatment for the DLMF macros and other TeX macros.

An example query is:
http://dlmf.nist.gov/search/search?q=expe+bessely+besselk

Where the user request was " I want to know of all formulas that contain these DLMF macros ".

Bruce should definitely be consulted about either him abstracting out his DLMF search into a standalone search engine or supervising a NIST-based student to do that for him.

The state of DLMF (the way Deyan knows of it! Not binding to be fully accurate!) is that the DLMF is served by a Java web service and the search capability is ad-hoc implemented as part of the web service, with further ad-hoc additions to the LaTeXML conversion process that enrich the produced HTML with special annotations coming from the macros.

One re-imagining of this, is to have the same search process harvest its data not from special ad-hoc annotations, but from the Content MathML symbol names directly. But only Bruce knows the technical feasibility of this vague approach.

**Comment by physikerwelt** [comment]
That's a build in feature of the latest update in the MediaWiki CirrusSearch extension that accesses elastic search. See for instance
http://drmf-beta.wmflabs.org/w/index.php?title=Special%3ASearch&profile=default&search=insource%3A%22\Riemannzeta%22+and+insource%3A%22\Eulergamma%22&fulltext=Search
