### ISSUE TITLE
latest latexml update causes failing MathSearch integration tests

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#47]
see
https://integration.wikimedia.org/ci/job/mwext-MathSearch-testextension-zend/232/console

after merging
https://github.com/brucemiller/LaTeXML/issues/549

**Comment by HowardCohl** [comment]
Do you think this has to do with this? : 

Moritz, when I ran perl Makefile.PL it complained 

Warning: the following files are missing in your kit:
lib/LaTeXML/Package/svg.cls.ltxml
Please inform the author.

**Comment by physikerwelt** [comment]
Mh. This is a problem. But I'm not sure if that's related. The funny thing is that the problem occours only for the specific configuratioin used in the test
```
			'wgMathDefaultLaTeXMLSetting' => array(
				'format' => 'xhtml',
				'whatsin' => 'math',
				'whatsout' => 'math',
				'pmml',
				'cmml',
				'nodefaultresources',
				'preload' => array( 'LaTeX.pool',
					'article.cls',
					'amsmath.sty',
					'amsthm.sty',
					'amstext.sty',
					'amssymb.sty',
					'eucal.sty',
					'[dvipsnames]xcolor.sty',
					'url.sty',
					'hyperref.sty',
					'[ids]latexml.sty',
					'texvc' ) ) ) );
```
I had a look at http://dlmf.nist.gov/LaTeXML/manual/commands/latexmlpost.html if there is a new option that disables or enables the tex annotation... but I chould not find one.
Maybe @dginev or @brucemiller have an idea where to start digging.

**Comment by physikerwelt** [comment]
However, I just removed the tex annotation from the test file. Now the test work again
```
<annotation encoding="application/x-tex" id="p1.1.m1.1c">{\displaystyle E=mc^{2}}

**Comment by brucemiller** [comment]
FWIW, the default (for some period of time?) had been to automatically add the TeX annotation whenever parallel markup was being created.  This was kinda inconsistent, and didn't give you a way to get the annotation w/pMML by itself.  Thus a new option was added ```--mathtex``` that adds it.

**Comment by physikerwelt** [comment]
@brucemiller: Just for future reference... will this option appear here http://dlmf.nist.gov/LaTeXML/manual/commands/latexmlpost.html when the website is updated the next time... or is there a better way to list the available options?

**Comment by brucemiller** [comment]
```latexmlpost --help```

**Comment by physikerwelt** [comment]
ok found it... I was looking in the math section only.
