### ISSUE TITLE
Add yourself to the MathSearch Project on phabricator

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#48]
https://phabricator.wikimedia.org/project/members/737/

**Comment by Dyiop** [comment]
The phabricator account creation is broken right now, according to the

**Comment by physikerwelt** [comment]
Can you link to the upstream issue on phabricator ?

**Comment by Dyiop** [comment]
They must have fixed the issue overnight, because I was able to sign in today. I have also added myself to the MathSearch extension project.

**Comment by physikerwelt** [comment]
@yusufameri1 can you do the same?

**Comment by yusufameri1** [comment]
@physikerwelt I added myself to the MathSearch Project on phabricator
