### ISSUE TITLE
Create a wiki user account on the drmf2015 instace

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#51]
* log in
* run ```mwscript createAndPromote.php --bureaucrat --sysop dyiop aSecurePassword```
see also https://www.mediawiki.org/wiki/Manual:CreateAndPromote.php
blocks #50

**Comment by Dyiop** [comment]
I created a new account with the user name "Dyiop", and was able to login in successfully.

**Comment by physikerwelt** [comment]
Well done. You can close this task now.

**Comment by Dyiop** [comment]
Could you link me to documentation on MWsciprt?
