### ISSUE TITLE
Customize config

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#52]
Learn how the configuration can be customized by enabling the debug toolbar
https://www.mediawiki.org/wiki/Manual:$wgDebugToolbar
Crate a new php file named LocalOverwrite.php on the instance in the folder
/vagrant/settings.d
Switch the config setting for wgDebugToolbar and see the effect on
http://drmf2015.wmflabs.org/wiki/Main_Page

**Comment by Dyiop** [comment]
To make the debug toolbar show up, I added the line "$wgDebugToolbar = true;" to LocalSettings.php

**Comment by Dyiop** [comment]
Now the toolbar shows up at the bottom of the page.
![screenshot](https://cloud.githubusercontent.com/assets/12139021/8212702/1e37948e-14eb-11e5-8512-0d2c8d6015ec.png)

**Comment by physikerwelt** [comment]
Great. Nie remove that again and put the line to a new file in the proposed folder. Local settings is managed by git and would be overwritten on the next update.

**Comment by physikerwelt** [comment]
When you are done you can close the task

**Comment by Dyiop** [comment]
Ok will do
