### ISSUE TITLE
Highlight query variables

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#53]
Currently the mathsearch extension highlights the parts that match the search result.
But the query variables can not be distinguished from the rest of the query.
This issue is about highlighting the query variables in another color.

**Comment by physikerwelt** [comment]
look at this example search for \sin ?x (?x is the querx variable)
![query](https://www.dropbox.com/s/7b5flxufphrqt4j/Screenshot%202015-06-17%2022.15.33.png?dl=0)
the first result
![screenshot 2014-10-23 21 43 38](https://cloud.githubusercontent.com/assets/2777736/8217591/afa79a06-153e-11e5-8ea8-add83d7e5fea.png)
sin \theta is highlighted in red. But \theta should have a different form of highlighting since it's the replacment for ?x

**Comment by physikerwelt** [comment]
@Dyiop Can you move this issue to https://phabricator.wikimedia.org/

**Comment by Dyiop** [comment]
https://phabricator.wikimedia.org/T105888
