### ISSUE TITLE
Create a latexmlpsgi test server

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#56]
We don't want to destroy the production latexmlpsgi server.
DRMF Specific macros are not required.
Any wmflabs instance could be used
Blocks
#55

**Comment by physikerwelt** [comment]
a guide is availible from here 
http://www.formulasearchengine.com/LaTeXML

**Comment by physikerwelt** [comment]
This is task is only required if #57 is not successful.

**Comment by yusufameri1** [comment]
`{"status_code":0,"result":"<math xmlns=\"http://www.w3.org/1998/Math/MathML\" id=\"p1.1.m1.1\" class=\"ltx_Math\" alttext=\"\\sin+x^{2}\" display=\"inline\">\n  <semantics id=\"p1.1.m1.1a\">\n    <mrow id=\"p1.1.m1.1.5\" xref=\"p1.1.m1.1.5.cmml\">\n      <mi id=\"p1.1.m1.1.1\" xref=\"p1.1.m1.1.1.cmml\">sin</mi>\n      <mo id=\"p1.1.m1.1.2\" xref=\"p1.1.m1.1.2.cmml\">+</mo>\n      <msup id=\"p1.1.m1.1.5.1\" xref=\"p1.1.m1.1.5.1.cmml\">\n        <mi id=\"p1.1.m1.1.3\" xref=\"p1.1.m1.1.3.cmml\">x</mi>\n        <mn id=\"p1.1.m1.1.4.1\" xref=\"p1.1.m1.1.4.1.cmml\">2</mn>\n      </msup>\n    </mrow>\n    <annotation-xml encoding=\"MathML-Content\" id=\"p1.1.m1.1b\">\n      <apply id=\"p1.1.m1.1.5.cmml\" xref=\"p1.1.m1.1.5\">\n        <plus id=\"p1.1.m1.1.2.cmml\" xref=\"p1.1.m1.1.2\"/>\n        <sin id=\"p1.1.m1.1.1.cmml\" xref=\"p1.1.m1.1.1\"/>\n        <apply id=\"p1.1.m1.1.5.1.cmml\" xref=\"p1.1.m1.1.5.1\">\n          <csymbol cd=\"ambiguous\" id=\"p1.1.m1.1.5.1.1.cmml\">superscript</csymbol>\n          <ci id=\"p1.1.m1.1.3.cmml\" xref=\"p1.1.m1.1.3\">𝑥</ci>\n          <cn type=\"integer\" id=\"p1.1.m1.1.4.1.cmml\" xref=\"p1.1.m1.1.4.1\">2</cn>\n        </apply>\n      </apply>\n    </annotation-xml>\n  </semantics>\n</math>","status":"No obvious problems","log":"\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/TeX.pool.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/eTeX.pool.ltxml... 0.01 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.25 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/LaTeX.pool.ltxml... 0.26 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/article.cls.ltxml... 0.02 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsmath.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsbsy.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amstext.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsopn.sty.ltxml... 0.00 sec) 0.07 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsthm.sty.ltxml... 0.01 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amssymb.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsfonts.sty.ltxml... 0.00 sec) 0.04 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/eucal.sty.ltxml... 0.01 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/xcolor.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/color.sty.ltxml... 0.02 sec)\n(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/graphics/dvipsnam.def... 0.13 sec) 0.41 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/url.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/hyperref.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/nameref.sty.ltxml... 0.00 sec) 0.04 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/latexml.sty.ltxml... 0.01 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/texvc.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/cancel.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/eurosym.sty.ltxml... 0.00 sec) 0.06 sec)\n\nltxpsgi (LaTeXML version 0.8.1; revision ca48d86)\nprocessing started Mon Jul 20 13:29:39 2015\n\n(Digesting TeX Anonymous String...\n(Processing content Literal String \\ensuremat...\n(Processing content Literal String \\sin+x^2...\n(Processing content Literal String \\begin{doc... 0.00 sec) 0.00 sec) 0.00 sec) 0.00 sec)\n(Building...\n(Loading compiled schema /usr/local/share/perl/5.18.2/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.03 sec). 0.08 sec)\n(Rewriting... 0.00 sec)\n(Math Parsing...1 formulae ...[1]\nMath parsing succeeded:\n   ltx:XMath: 1/1\n   ltx:XMArg: 1/1\nSymbols assumed as simple identifiers (with # of occurences):\n   'x{italic}' (1)\nSet MATHPARSER_SPECULATE to speculate on possible notations.\n 0.01 sec)\n(Finalizing... 0.00 sec)\nConversion complete: No obvious problems.\n\n(post-processing...\n(Scan processing... 0.00 sec)\n(CrossRef processing... 0.00 sec)\n(MathML::Presentation[w/MathML::Content] processing... 0.00 sec)\n(XSLT[using LaTeXML-xhtml.xsl] processing... 0.00 sec) 0.01 sec)\nPost-processing complete: No obvious problems\nprocessing finished Mon Jul 20 13:29:`
