### ISSUE TITLE
$wgMathDisableTexFilter being reset somewhere

### ISSUE THREAD

**Issue by plato2000** [DRMF/DRMF#64]
`$wgMathDisableTexFilter` seems to reset itself to 'never' even after setting it to 'always' in a localSettings.php file. This was resolved temporarily by setting the variable right before its use somewhere in MathRenderer.php, but it seems to have reset itself already. This causes the LaTeXML renderer to not even try to parse custom LaTeX commands.

**Comment by physikerwelt** [comment]
hhvm has been replaced by mwrepl
 * To interactively evaluate PHP and MediaWiki code, run 'mwrepl' or 'mwrepl somewikidbname'.
can you update the drmf2016 instance to the latest vagrant version
in the main instance
```
cd /vagrant
git pull
vagrant git-update
vagrant reload --provision
```
should to the job

**Comment by physikerwelt** [comment]
^^ I saw you did that
now you see the actual value
```
echo $wgMathDisableTexFilter;
never
```

**Comment by physikerwelt** [comment]
... I found the problem via 
```bash
vagrant@mediawiki-vagrant:/vagrant$ grep 'MathDisableTexFilter' . -R
```
It was in Localsettigs
