### ISSUE TITLE
LaTeXML renderer blanks out on some LaTeX expressions

### ISSUE THREAD

**Issue by plato2000** [DRMF/DRMF#69]
For example, [here](http://drmf2016.wmflabs.org/wiki/Formula:ZE.EX.PR02), it renders the fraction 1/2 as \tfrac12 instead of the actual fraction. Oddly enough, the same LaTeX expression (linked to from [here](http://drmf2016.wmflabs.org/wiki/Definition_and_Expansions#ZE.EX.PR02)) it seems to render fine.

**Comment by plato2000** [comment]
To clarify, it is the fallback renderer that does this.

**Comment by physikerwelt** [comment]
@plato2000 I don't know what to do. I think it's better if you assign task eiter to you or to me. However, note that I'm working full time now on another job.
