### ISSUE TITLE
Setup Java backend for DRMF

### ISSUE THREAD

**Issue by AndreG-P** [DRMF/DRMF#75]
* Search engine doesn't work reliable.
* LaTeXML server is slow
* Translation is not available on the website

**Comment by AndreG-P** [comment]
@physikerwelt 
Created an endpoint in vmext-demo. See: http://vmext-demo.wmflabs.org/swagger-ui.html#!/math-controller/translationUsingPOST
As an example, try our use case:
```
cas   = Maple
latex = \JacobiP{\alpha}{\beta}{n}@{\cos@{a\Theta}}
```

The response will be a json object:
``` json
{
  "result": "JacobiP(n, alpha, beta, cos(a*Theta))",
  "log": "Information about the conversion process: ..."
}
```

**Comment by physikerwelt** [comment]
@AndreG-P I would prefer one assignee per ticket. otherwise, nobody feels responsible.

**Comment by AndreG-P** [comment]
Got it, please close this issue when you are happy with the endpoint solution.

**Comment by physikerwelt** [comment]
I think this is not entirely solved, or?

**Comment by AndreG-P** [comment]
@physikerwelt Can you specify what's missing and open issues on [vmext-demo](https://github.com/ag-gipp/vmext-demo/issues) accordingly?

**Comment by physikerwelt** [comment]
Can you please check if the backend implementation solves the 3 issues from the backend perspective and then create a new ticket to reconfigure the demo to use the backend.

- [ ]    Search engine doesn't work reliable.
- [ ]    LaTeXML server is slow
- [ ]   Translation is not available on the website

**Comment by AndreG-P** [comment]
There is nothing to do here since vmext-demo endpoint is far ahead of this ticket.
